server:
  port: 7777
  context-path: /scala-boot

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/imoocbootscala?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
